### ISSUE TITLE
Projeto para o Debian

### ISSUE THREAD

**Issue by Nilsonfsilva** [helviojunior/turbosearch#2]
Olá Hevio!
Desde já sou um grande admirador do seu trabalho!
Vendo essa ferramenta, gostei bastante.
Como empacote projetos para o Debain, reolvi empacota-la.

Porem para fazer isso, preciso que ela esteja sob alguma licença.

Caso haja interese de ter essa ferramenta no debian, é só liberar o projeto sob alguma licença.
Obrigado!

**Comment by helviojunior** [comment]
Obrigado meu amigo por todo o apoio. Realizado.
